### ISSUE TITLE
Needs update for new tags

### ISSUE THREAD

**Issue by SAMahmood-hub** [Xeio/RecruitTagScanner#1]
I'll check out the code myself to see if I can figure it out but I wanted to bring that up!

**Comment by SAMahmood-hub** [comment]
And seeing your code, looks like you use aceship to get tags and operators, not sure if anything else needs update but code looks fine as is!

**Comment by Xeio** [comment]
Yeah, it's automatic as long as Aceship updates.

You may be able to "force" a quick sync by clearing cache on the app itself if needed, I'm not 100% on how quickly the caching mechanism expires on Android.
