### ISSUE TITLE
[Request update] New, certain tags combos are not working

### ISSUE THREAD

**Issue by snwefly** [Xeio/RecruitTagScanner#2]
Could you please update the application?

Thanks

**Comment by Xeio** [comment]
Which tags combinations aren't working? The application auto-updates to keep in sync with Aceship (at least, if Aceship is still updating).

**Comment by snwefly** [comment]
Application settings

![Alt Text](https://raw.githubusercontent.com/snwefly/neeee/main/Screenshot_20220130-212259.png)

![Alt Text](https://raw.githubusercontent.com/snwefly/neeee/main/Video%20Recorder%201.gif)


Since i didn't get +4 * today i used your image 😊 and it didn't detect and i used another <4* image and got the response.

Far i a remember, scanner is not working for anything above 4* combination .

Using nox emulator, android 7, I used it few months ago and it worked fine btw.

Thanks

**Comment by snwefly** [comment]
Just in case if OCR didn't work on low res/already captured image.

I got 4* combo and scanner didn't pick up

![Alt Text](https://raw.githubusercontent.com/snwefly/neeee/main/Video%20Recorder%202.gif)

combo result from aceship


![Alt Text](https://raw.githubusercontent.com/snwefly/neeee/main/Untitled.jpg)

**Comment by Xeio** [comment]
Hmmm, so the app is designed to _always_ pop something up, either the "no 4*" toast, or a full notifcation if it finds a 4* or better match. If you don't see any popup, that means that the app didn't work.

This means there's one of two issues, either the screenshot isn't being parsed correctly (it can't find all the tags using OCR), or it doesn't see the screenshot being generated. The OCR _probably_ isn't the issue (though I can't rule it out).

For the screenshot file it looks for the words "Arknights" or "Screenshot" in the name of the file, so you may want to check what the name of image files are in the file on that emulator if you can provide one as an example.

**Comment by snwefly** [comment]
>either the screenshot isn't being parsed correctly (it can't find all the tags using OCR), 

>it doesn't see the screenshot being generated. 

>The OCR probably isn't the issue (though I can't rule it out).

I don't know kotlin but from end user tastings , none of the above seems to be the issue.

application does output "no 4* found" notification without any fails but it didn't output any notification when its finds +4* every single time.

since its only fails to notify when there is a +4*, seems image is parsed correctly and able to get info from aceship

Image from the nox player

https://raw.githubusercontent.com/snwefly/neeee/main/Screenshot_20220131-232642.png

**Comment by Xeio** [comment]
Ok, so then the problem is most likely with the notifications themselves. Possibly there's some setting that's blocking all notifications for the app?

**Comment by snwefly** [comment]
"no 4* found" notification overlay is displayed  so i don't think any settings or permission issue blocking all notifications

Something definitely  blocking or stopping the notifications when +4* founds

Things i already tried 

- run with root and without root
- changed around permission settings in your application
- clean install
- grant full permission via ADB
- disabled firewall on the router (just incase its blocked any request)

things left to test, previous versions of nox emulator and android 😑

What emulator and android version you're using?

**Comment by Xeio** [comment]
The "No 4*" popup is technically what android calls a "Toast" not a "Notification". Android treats them differently so something blocking one may not affect the other. I know some manufacturers do weird things, but usually you can fix them by going into settings for the app fixes that which it sounds like you did.

I generally play on my actual phone with Android 11 (though sometimes from my PC using Your Phone to screen link). I tested on one of the official emulators back when I was doing more active dev on it but don't have anything set up at the moment. I don't know anything about Nox to comment.

**Comment by snwefly** [comment]
I did couple of tests on other emulators, few previous versions of android 7 ∈ 9 still same results.

I don't have a smart phone so couldn't test it on in any of the native environment  .

When you get any free time pretty please look at the source code again 😊.

Thanks
